# sources 
SRC    := $(filter-out testing.c, $(wildcard *.c))
TESTSRC = testing.c 
OBJ     = $(SRC:.c=.o)

# target
TARGET     = ashell
TARGETTEST = test

# cflags
CC       = gcc
STD      = -std=c2x
WARN     = -Wpedantic
DEBUG    = -g -DDEBUG
LIBS     = -lutil
SANITIZE = -fsanitize=undefined,address
CFLAGS   = $(STD) $(WARN) $(DEBUG) $(SANITIZE)

# default build
all: $(TARGET)

# linking 
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $^ -o $@ $(LIBS)

# building
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# test build
# Intended for testing specific header files. 
test: $(TARGETTEST)

$(TARGETTEST): $(OBJ) testing.o
	$(CC) $(CFLAGS) $^ -o $@ $(LIBS)

testing.o: testing.c
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	rm -f $(OBJ) $(TARGET) $(TARGETTEST)

.PHONY: all clean test
